name: William Lloyd Co.
favicon: null
layout_spectrum: 0.07619414385408163
typography_spectrum: 0.7822913825511932
title: The William Lloyd Company.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6663406994193792
  lightness: 0.25437268102541566
  saturation: 0.36649229447357357
  rhythmicContrast: 0.8052689214237034
purpose: []
