name: William Lloyd Co.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7822913825511932
title: The William Lloyd Company.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf7e9'
    - '#14466a'
    - '#4b9ac7'
    - '#7db4d0'
    - '#bfd7dd'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.8052689214237034
purpose: []
